modLoader = "javafml"
loaderVersion = "[42,)"
license = "MIT"

[[mods]]
modId = "agric"
version = "${file.jarVersion}"
displayName = "Agric"

description = '''Agric - A Mod to expanding upon the Minecraft Vanilla farming system'''

[[dependencies.agric]]
	modId = "forge"
	mandatory = true
	versionRange = "[42,)"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.agric]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.19.1,1.19.2)"
	ordering = "NONE"
	side = "BOTH"
